title = About: Klungbot

closeAboutBox.Action.text = &Close

appDescLabel.text=<html>\nAngklung Robot Player with Doremi Music Engine and Editor\n<ul>\n<li>Lead Developer: Eko Mursito Budi</li>\n<li>Innovators: Karismanto Rahmadika, Krisna Diastama</li>\n<li>Software Engineers: Fariza Dian Prasetya, Alvin Nurhadi</li>\n<li>Hardware Engineers: Sutriana, Sholeh Taryana, Bolo Dwipriatmo</li>\n<li>Craftmen: Sunata, Mamat</li>\n<li>Musician: Asep Suhada</li>\n</ul>\n\nCopyright: Eko Mursito Budi, 2011<p>\nEmail: mursito@gmail.com<p>\n</html>\n
#NOI18N
imageLabel.icon=klungbot-logo1.png
appTitleLabel.text=Klungbot version 3.0
